# Generated by Django 3.2.2 on 2021-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20210507_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengers',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='passengers',
            name='adhaarId',
            field=models.BigIntegerField(default=''),
        ),
    ]
