# Generated by Django 3.2.2 on 2021-05-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20210507_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengers',
            name='adhaarId',
        ),
        migrations.AddField(
            model_name='passengers',
            name='idImage',
            field=models.ImageField(default='', upload_to='ticket/images'),
        ),
    ]
