# Generated by Django 3.2.2 on 2021-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20210507_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='idImage',
            new_name='id_proof',
        ),
    ]
