# Generated by Django 3.2.2 on 2021-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(default='', max_length=50)),
                ('id_proof', models.CharField(default='', max_length=50)),
                ('contact_no', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
