# Generated by Django 3.2.2 on 2021-05-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210506_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='', max_length=50)),
                ('destination', models.CharField(default='', max_length=50)),
                ('cost', models.IntegerField(default='250')),
            ],
        ),
        migrations.RemoveField(
            model_name='passengers',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='bus',
            name='busConductor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='conductorContact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='number_seats',
            field=models.IntegerField(default='250'),
        ),
        migrations.AddField(
            model_name='passengers',
            name='image',
            field=models.ImageField(default='', upload_to='ticket/images'),
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='bus_rou',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticket.bus'),
        ),
        migrations.CreateModel(
            name='Bus_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.passengers')),
                ('sch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.schedules')),
            ],
        ),
    ]
