# Generated by Django 3.2.2 on 2021-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210517_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Message', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
